name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: deploy upstream
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.UPSTREAM_HOST_URL }}
          localDir: dist
          password: ${{ secrets.UPSTREAM_PASSWORD }}
          remoteDir: ${{ secrets.APEX_DOMAIN_URI }}/httpdocs/${{ secrets.SUBDOMAIN_URI }}
          user: ${{ secrets.UPSTREAM_USERNAME }}
          options: '--delete'
